### PR TITLE
Image Priorities: Dynamic image ranks based on Pref settings

### PR DESCRIPTION
**Pull request by EndOfLine369**
https://github.com/ZeroQI/Hama.bundle/issues/263

This will remove all hard coded priority numbers to be determined by a call to `common.poster_rank()`

### CODE REVIEW

**Comment by ZeroQI** [comment]
Remove non-functioning "TheTVDBv2.GetMetadata" argument
- https://github.com/ZeroQI/Hama.bundle/pull/408/commits/e7e519b33bfab81d331b32e0608701ef4684b10d
- TheTVDB is gathered before AniDB now so the code is useless indeed. Also, the fact it is a movie is irrelevant with the way rank is calculated

Create "common.poster_rank()" for use in other modules
- https://github.com/ZeroQI/Hama.bundle/pull/408/commits/88faaa82bcf2d1b9415320a7f0dcb63e9e38307b
- i like the coding a lot for poster_rank(). 
- Banner "T--M" is wrong (TV-Series Movies) in DefaultPrefs.json (pretty sure it's my bad) when compared with https://github.com/ZeroQI/Hama.bundle/wiki/Plex-Metadata-Fields-Available (TV-Show Season Episode Movies Album Group(Artist) Track) which show it as "TS––" (TV-series and Seasons) and confirmed with https://web.archive.org/web/20150113085312/http://dev.plexapp.com/docs/agents/models.html (tvshows season). Wondering which client use banner display though , but better leave supported fields in the code for now

Convert to "common.poster_rank()"
- https://github.com/ZeroQI/Hama.bundle/pull/408/commits/a49e120365dd73774089e6675859139cc5b5f11c
- i like how it flows logically reducing code and variables use

Update to rank calculation
- https://github.com/ZeroQI/Hama.bundle/pull/408/commits/1f05e0348274f76c052414c555f7e14927009739
-  from 'localhost' to '127.0.0.1' back handled by "Bring in line with master to use 'localhost'"
- validate_keys means not listed posters will be removed, does that remove manually added posters? "code comment" show it is to update rank, which is important for existing libraries
- rank_adjustment is used when calling function ? Can't remember which code part does that

**Comment by EndOfLine369** [comment]
**Added 3 more commits for you to look at.**

> Thanks as well but the mod to the plex token, genius, would never have checked that!

I had known about the Plex putting in the env variable into the 127.0.0.1 requests for a long time. It just never clicked to just do that ourselves. So just had to do a quick test to find the right env variable to use in ASS compared to HAMA (not the same env variable).


**These are the two you had questions about:**
> * validate_keys means not listed posters will be removed, does that remove manually added posters?

Not that I noticed, as long as they are the selected image. As when they are manually added, I believe they are added at rank 1 so no other image will beat it. And even if the image is removed from the list but is higher and active, it will not go away.

> * rank_adjustment is used when calling function ? Can't remember which code part does that

Was just some added functionality if we ever want to adjust the outcome. Best to let the function handle it so it does not go over/under the 1-100 values in stead of having to replicate that in one of the module post call.

**Comment by ZeroQI** [comment]
All looks good in the submit, i somehow missed only posters were scrubbed, good fix for that
akes sense the adjustment, just couldn't see it used anywhere...

I can download and upload but cannot change active image...

**Comment by ZeroQI** [comment]
I did create a branch from MAL agent new API if you saw, but have not tested it

**Comment by EndOfLine369** [comment]
Well, at the very least the first meta load will put them at the right priorities. And any pref updates/reload will have the image order correct when they view the posters available in the edit screen.

**Pull request merged**
