### PR TITLE
Fetch Posters, Banners and Background Art from fanart.tv

### PR DESCRIPTION
**Pull request by KingJ**
Although fanart.tv isn't always as comprehensive as the TVDB for Posters, Banners and Background Art, all of the ones it has tend to be of very high quality and are often unique.  This pull request adds support to Hama for downloading these images from fanart.tv and loading them in to Plex. Development was done against the latest trunk version of Hama, and tested with the latest Absolute Series Scanner and Plex Media Server version 1.1.2.2680. Here's what's working at the moment;

- Posters, Banners and Background Art for shows, based off their TVDB ID.
- Season Posters for Seasons
- Posters and Background Art for movies, based off their TMDB ID. If a movie is missing a TMDB identifier in the master anime list but the IMDB ID is present, it will query TMDB using the IMDB ID to get the TMDB ID.
- New options have been added in the agent settings to control the download of Posters/Banners/Background Art. As with the other artwork fetch options, i've set the ones for fanart.tv to be disabled by default.

As for what's not working/any caveats;
- A new folder (FanartTV) needs to be created in the DataItems folder so that the images can be saved locally. This is not currently present in Plug-in.Support.folders.zip, so unless the folder is manually created the images won't download.
- For the main show entry, Posters and Season Posters will be downloaded (I chose to do this as when AniDB splits seasons, it's nice to be able to still have "Season 1" etc as the poster on the main entry in Plex).
- For the "Specials" season, any Specials seasons posters should be downloaded **but this is untested** as I couldn't find any entries on fanart.tv that had a Season 0 seasonposter and were also in my collection!
- When the AniDB show entry is a TVDB season other than Season 1, the "Season 1" posters in that entry should be those of the actual season. E.G. For a show on AniDB that is listed as Season 2 on TVDB, the "Season 1" posters would include those that are listed as Season 2 on fanart.tv. This mostly works **but not in all cases**. The one case I found that doesn't work is where a show has two AniDB entries but only one TVDB entry and someone has uploaded it as split-seasons on fanart.tv  (e.g. Fate/Stay Night: Unlimited Blade Works has a 2014 and 2015 entry on AniDB, but is listed as a single season on TVDB. On fanart.tv, someone has uploaded seperate Season 1 and 2 banners). I'm not sure how best to solve this, but it seems like an edge case really - I think most of the time we should be trusting the TVDB season when querying fanart.tv.
- The API key used for fanart.tv is currently registered to my account under the name "Hama Dev". If you merge this PR, you might want to register a new application API key for Hama 'Prod'. fanart.tv also supports [personal API keys](https://fanart.tv/2015/01/personal-api-keys/) in addition to application API keys. A personal API key lets a user gain access to newly uploaded artwork 2 days after upload, instead of 1 week after upload (VIPs can also use a personal API key to gain access to newly uploaded artwork immediately). I haven't implemented support for personal API keys, but it's on my todo list.
- I have only tested it in anidb mode, testing with the various tvdb modes hasn't been tested and I have no idea what will happen if these modes are used! At a guess, the Posters, Banners and Background Art for the show should download correctly but the art for each season probably won't as they've been hardcoded to season 0/1 as appropriate.
- I'm not sure if caching is always working correctly - in the logs I occasionally see a Not Caching message with the reason `content type 'image/jpeg' not cacheable in Agent plug-ins`.

I think that covers everything. This is my first ever serious pull request so please let me know if i've done anything wrong! I welcome any feedback on the code itself, i've tried to keep it clean, readable and commented as appropriate. Even though fanart.tv might not have the greatest selection of extra artwork, it'd be great to have this in Hama so we've got even more artwork to choose from! :smile:

### CODE REVIEW

**Comment by ZeroQI** [comment]
Excellent, disn't know they did posters too...
You managed season posters? That's gas... (irish expression)
Images are never cacheable, which is why i did my own cache, so ignore the message.
If posters are pulled, need to check priority is lower than tvdb but higher than anidb.
Seem like when series have missing pics this comes in handy...
Let me check code and promote you to collaborator

**Comment by ZeroQI** [comment]
Merged, changed api key and did heavy code reduction, trying to keep it short...
Hopefully i didn't break anything.
Well done, this will help covering some series, very nice work

**Comment by KingJ** [comment]
Awesome! Thank you very much for merging this and making me a committer :smile: . I'll try and get my code to fit the same style for any future PRs so you don't have to reduce it for me. I've had a look over the reduced code and it looks to be OK - i'll test it again and fix any issues that pop up.

I can't take any credit for the AMV scanner/agent, I just fixed a small error in the documentation. Hoping to contribute more where I can to the things I use though - it's good to give back! I want to add support for personal fanart.tv API keys but I think that's all that's left to do, other than perhaps filtering/prioritising posters etc by their language and the user's language.

**Comment by ZeroQI** [comment]
i know i code a bt abnormally, but it would increase too much the length and i can no longer correct on my phone where i do most of it...
I personally don't see the need for personal key if app key works
Filtering/prioritizing posters etc by their language and the user's language, could be useful.
Well done, it is the only worthwhile addition that could be, as i cannnot see what we could add more at that point
Maybe improve the search for tvdb only series and maybe tmdb series... need to think about htat...

**Comment by KingJ** [comment]
The only benefit of personal API keys is access to artwork earlier - free personal API keys can access new artwork 2 days after upload and "VIP" personal API keys can access immediately. When only an application key is used only artwork that was uploaded more than a week ago is returned, so personal API keys would be useful for series which are currently airing so they can get the latest artwork. It wouldn't be too much work for me to add support for it, it's just another parameter in the URL.

The next week or so will be a bit busy for me so I might not be able to do it for a short while, but i'll open up a new PR once i've done this as well as tweaked the image priority to account for the image's language.

I'm impressed that you normally correct on your phone, the small screen size would drive me crazy!

**Comment by ZeroQI** [comment]
Ok there is an interest...
Galaxy note 3, not so small screen... I do small correction on there and code clearing when not in front of computer...

**Pull request merged**
