### PR TITLE
Skip episode if another is mapped to its value

### LINKED ISSUE #500: Multiple TVDB episodes mapped to the same anidb episode
So I found an issue that probably is happening to a bunch of other shows where episodes are being mapped to two different seasons at the same time on TVDB.

Example:
- [AniDB Link](https://anidb.net/anime/13493)
- [TheTVDB Link (Season 3)](https://thetvdb.com/series/sword-art-online/seasons/official/3) 

File to test it:
[!] file:       "/media/Ani-Test/Sword Art Online Alicization (2018) [anidb-13493]/Sword Art Online Alicization  - 03.mkv"

Some logs:

> --- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 13493, TVDBid: 259640, defaulttvdbseason:    3, offset:   0, TMDBid:        , IMDBid:           , name: Sword Art Online: Alicization
    - season: [ 0],           [ 0], range:       [000-000], offset:   0, text: 1-24;2-25
             -----          ------
             13493          259640
[ ] collection: TVDBid '259640' is part of collection: '['Sword Art Online Collection']', related_anime_list: ['8692', '10022', '10376', '11681', '13493', '14796', '15146']
[ ] studio: 
--- return --------------------------------------------------------------------------------------------------------------------------------------------------
AniDB_id: '13493', AniDB_id2: '13493', AniDBid: '13493', TVDB_id: '', TVDB_id2: '259640', TVDBid: '259640'
mappingList: {
  'defaulttvdbseason': '3',
  'defaulttvdbseason_a': False,
  'episodeoffset': '0',
  'name': 'Sword Art Online: Alicization',
  'possible_anidb3': False,
  's1e1_mapped': False,
  'season_map': {'13493': {'max': '3', 'min': '3'}},
  'TVDB': {'s0e24': ('0', '1', '13493'), 's0e25': ('0', '2', '13493'), 's3': {'13493': '0'}},
  'tvdbcount': 1}

Episodes match:

> [X]    s1e3 s01e003 anidbid: xxxxxxx air_date: 2012-07-22 abs_number: 3, title: The Red-Nosed Reindeer
and

> [X]    s3e3 s01e003 anidbid:   13493 air_date: 2018-10-21 abs_number: 53, title: The End Mountains

---

ASS Logs:

> =============================================================================================================================================================
Call: "Plex", path: "Sword Art Online Alicization (2018) [anidb-13493]", folder_show: "Sword Art Online Alicization (2018) [anidb-13493]", dirs (0), files (1)
=============================================================================================================================================================
Forced ID (series folder) - source: "anidb", id: "13493"
"Sword Art Online Alicization (2018) [anidb-13493]" s01e         3                         "Word Search" "" "Sword Art Online Alicization  - 03.mkv"
=============================================================================================================================================================

This is an issue because in this example it sometimes sets thumbs from the season 1 episode as the default thumb (while downloading the correct season 3 episode thumb).

### PR DESCRIPTION
**Pull request by cameronkinsella**
If a TVDB episode is mapped to a value that already exists in TVDB then duplicate episodes will be matched. This causes only the final match to be used for metadata, which could be the wrong one.

This fix should resolve the episode name mapping issue for anidb to TVDB.

Since thumbnails are still stored by their mapped values, this does not resolve the issue where the incorrect thumbnails are sometimes chosen as the default. In this case, the correct thumbnail will still be available as the second choice when editing the episode in plex, so you can manually fix them without too much effort.

Partially resolves #500

### CODE REVIEW

**Comment by cameronkinsella** [comment]
I have only tested this with one affected series (Monogatari series), so I would appreciate it if someone else could test it as well.

**Comment by natyusha** [comment]
Tested with several series that were previously mapped incorrectly and this fixed all of them.

**Comment by zyfinity01** [comment]
Does this also fix the poster being incorrect such as in issue #500 ?

**Comment by plato79** [comment]
This didn't fix the problem in https://github.com/ZeroQI/Hama.bundle/issues/500#issuecomment-1171461901

**Comment by natyusha** [comment]
The pr does what it says and fixes the matching for series that share things under the same entry on tvdb (multiple seasons / specials / ovas / movies).

I saw "Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou" used as an example of a movie that isn't matching correctly but that is actually an issue with anime-list-master.xml which is pointing to the wrong episode.
```
<anime anidbid="14840" tvdbid="330139" defaulttvdbseason="0" episodeoffset="1" tmdbid="610892" imdbid="tt10477558">
  <name>Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou</name>
</anime>
 ```
 
 It is pointing to season 0 of the main series (which doesn't contain any trace of the movie).

**Comment by plato79** [comment]
Well, so the problem in #500 is on the metadata and not in the code then if I understand correctly..

The weird thing is when I undo https://github.com/ZeroQI/Hama.bundle/commit/b475676bcc72fe2a9076b8d86394d1acf7a87bf0 this appear correctly so it was pulling the data another way before this fix.

**Pull request merged**
