### PR TITLE
Fix "Missing Episodes" for AniDB Movies / Sort Error Logs

### PR DESCRIPTION
**Pull request by EndOfLine369**
Movie entries in AniDB do not show correct entries in the "Missing Episodes" log. If you have the "Complete Movie"(ep1), it still shows your missing ep2 & ep3 as they are separate entries for "Part 1 of 2"/"Part 2 of 2" or "Part X of 3" etc.

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@MagellanSails / @sven-7 
If one of you would be so kind to test.
https://raw.githubusercontent.com/ZeroQI/Hama.bundle/d7b1e6e7c72831aa831c290b9ca495c0fee152f6/Contents/Code/__init__.py

You will see entries in the log like this of "movie_ep_groups"/"new missing_eps"
As well as not showing in "Missing Episodes.htm" when `new missing_eps: []` is empty.
```
2016-06-07 21:59:16,060 (-b5bc470) :  DEBUG (__init__:651) - movie_ep_groups: [{'s1e1': 'found'}, {}, {'s1e3': 'missing', 's1e2': 'missing'}, {}, {}, {}, {}]
2016-06-07 21:59:16,061 (-b5bc470) :  DEBUG (__init__:651) - new missing_eps: []
2016-06-07 21:59:16,062 (-b5bc470) :  DEBUG (__init__:651) - Update() - DURATION: 5700000, numEpisodes: 1
2016-06-07 21:59:16,062 (-b5bc470) :  DEBUG (__init__:651) - Locked 'anime-list anidbid missing' [True, 1465354756]
```

**Comment by EndOfLine369** [comment]
I've also added in sorting of the error logs
https://raw.githubusercontent.com/ZeroQI/Hama.bundle/83907dddc35db674f96bf07d983c325fb5464ea6/Contents/Code/__init__.py

EX "TVDB season posters missing.htm":
```
tvdbid: 79134 | Title: ''
tvdbid: 137801 | Title: ''
tvdbid: 146921 | Title: ''
tvdbid: 283925 | Title: 'Ai: Tenchi Muyo!'
tvdbid: 120041 | Title: 'Angelique'
tvdbid: 279984 | Title: 'Blade Dance of the Elementalers'
tvdbid: 306847 | Title: 'Cerberus'
...
```

**Comment by ZeroQI** [comment]
@EndOfLine369: Excellent work, that is a neat log.
All tvdb id with no title above are no longer valid, that explain the lack of titles.
all that is left is maybe pad the tvdbid with: tvdbid.ljust(6, ' '))

**Comment by sven-7** [comment]
Sorting logs works perfectly -- well done!  

As for the movies, I'm not sure I'm much help.  I currently have two libraries (Anime Series - using ASS and HAMA) and then Anime Movies (Plex Media Scanner and TheMovieDB).  In the latter library I have a handful of things custom mapped with HAMA to AniDB, but largely I've found the movie descriptions, artwork, metadata, etc...to be much better from TheMovieDB than AniDB.  

I'll attempt to make a side library to test this -- do you envision people having their movies and series in one library or in a separate library using HamaMovies?

**Comment by ZeroQI** [comment]
To be honest separating movies and series is a pain for anime and make no sense (one piece, Detective Conan) apart for motion pictures with no series BUT any metadata media software separate movies and series including plex, however i managed to make all work with series, and that is something to my knowledge only Hama can do.

I am considering making a movie scanner from the series scanner, but the default scanner is decent
you can force a tmdb id with hama too if you so wish. 

Please check and give me a movie example i know the posters are bad in anidb, which is why i take them from themoviedb tvdb imdb also. Does that mean Hama is not pulling TMDB poster like it should ? Or is the priority inadequate ? please check...

We could add in an option to prefer themoviedb, but if you prefer themoviedb for movies, you might as well have a separate library for movies with it as an agent, as it would be possibly quite complex as we already support 2+ metadata sources.

**Comment by ZeroQI** [comment]
sorry merged the commit but it closed the pull request... I am so bad with git...

**Comment by sven-7** [comment]
I do presently have separate libraries. 

I separate them because I have a lot of motion pictures and like being able to see them separated out from series.  I also do not like how when having movies in a Plex "TV Series" library, tries to consider them a season/episode.  Picky on my part, but it's just how I like to keep my libraries. Example:

screen shot 2016-06-08 at 10 38 06 am
screen shot 2016-06-08 at 10 39 27 am


Looking at it -- I think the poster options are working well.  It seems to be pulling from all databases as intended. I think this is not an issue.

The default scanner has worked quite well with HamaMovies as a Movie library, which I like.  I leave the default on TheMovieDB because I mainly have anime motion pictures, but for specials like One Piece, Detective Conan, Lupin III -- I have those mapped with HAMA.  

The reason I use TheMovieDB is because I get trailers for motion pictures, ratings, etc...

Here are two movies mapped to HAMA:

screen shot 2016-06-08 at 10 23 48 am

screen shot 2016-06-08 at 10 33 01 am


Here are the same two mapped to TheMovieDB:

screen shot 2016-06-08 at 10 23 07 am
screen shot 2016-06-08 at 10 32 32 am


You can see there are some small differences between the two.  For Anthem of the Heart, the Writer, Director, cast info is much more detailed than AniDB (which overall has poor movie data).  You'll also notice Anthem of the Heart has a tagline below it.

**Pull request merged**
