### PR TITLE
EOL Merge

### PR DESCRIPTION
**Pull request by EndOfLine369**
Major Updates:
* Logging Overhaul
* Move HAMA core file loads into the 'Start' function from generation at import (https://github.com/ZeroQI/Hama.bundle/commit/62bbe6de57d28b1587f7d529484da24f21610010)

Medium Updates:
* S0 AniDB-TVDB mapping (https://github.com/ZeroQI/Hama.bundle/commit/bbb78ac350d451ef94f18cf7724e0d0148dea9bc & https://github.com/ZeroQI/Hama.bundle/commit/e23fbcf37cef0e31687e61929b8ae2dc3308003a)
* Fix AnimeLists AniDBid selection (https://github.com/ZeroQI/Hama.bundle/commit/4a1db809c6c60555ba882b828613008227ef1b89)

Minor Updates:
* TheMovieDB title fix (in https://github.com/ZeroQI/Hama.bundle/commit/3ea23944919205b1fa3a5362230389a9c9836f63)
* TVTunes url pull fix (in https://github.com/ZeroQI/Hama.bundle/commit/3392fc6157dc39fb5a2f1d27364f71916fba3cd1)

### CODE REVIEW

**Comment by ZeroQI** [comment]
i like "Move HAMA core file loads into the 'Start' function from generation at import "
We can code a command like when we custom search a series name "clear-cache" to update core files

S0 AniDB-TVDB mapping: excellent. 
Remove need for 'AllInts' funciton: i like code simplicity
Animelist fix important since it's the heart of the engine

**Comment by EndOfLine369** [comment]
Added in handle for str return in AniDB & MAL

**Comment by EndOfLine369** [comment]
All good to you @ZeroQI ?

**Comment by ZeroQI** [comment]
More that good, excellent, had thought about doing that str handling, and the code shortening brilliant, i wished i did that as i like code shorter, makes it easier for me to follow

**Comment by EndOfLine369** [comment]
Merged 😄

**Comment by EndOfLine369** [comment]
Hey @ZeroQI, had a chance to review the new logging? Anything still look out of place you want me to try and update? The logging should now be nicely formatted and the same format for all source logging. The dict printing with variable depth was definitely tricky.

**Pull request merged**
