### PR TITLE
Fix AniDB metadata pull when using absolute numbering in 'tvdb3'/'tvdb4'

### PR DESCRIPTION
**Pull request by EndOfLine369**
Hi @ZeroQI,

Please review.
Examples of pulls now working to pull AniDB metadata.

Example of 'tvdb4':
```
=== Update ==================================================================================================================================================
id: tvdb4-275798, title: Fate/Zero, lang: en, force: True, movie: False
start: 2018-10-29 09:07:51,717685
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - tvdb_numbering: True
[+] AniDBid:  8160, TVDBid: 275798, defaulttvdbseason:  1, offset:   0, name: Fate/Zero
    - season: [ 0],           [ 0], range:      [000-000], offset:   0, text: 1-3;2-4;3-5;4-1;5-2
[+] AniDBid:  8880, TVDBid: 275798, defaulttvdbseason:  1, offset:  13, name: Fate/Zero (2012)
    - season: [ 0],           [ 0], range:      [000-000], offset:   0, text: 1-0;2-6;3-7;4-8
[+] AniDBid:  9907, TVDBid: 275798, defaulttvdbseason:  0, offset:   0, name: Fate/Zero Cafe
    - season: [ 1],           [ 0], range:      [000-000], offset:   0, text: 1-0
             -----          ------
              8160          275798
...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
AniDBid: 8880, url: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8880
common.LoadFile() - file cached - CacheTime: 'Mon Oct 29 06:14:08 2018', Limit: 'Sun Nov  4 08:07:52 2018', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8880', Filename: 'AniDB/xml/8880.xml' file_valid: 'True'
[ ] 'title': Fate/Zero (2012), original_title: Fate/Zero (2012), language_rank: 0
[ ] Roles (creators tag): {'directors': ['Aoki Ei'], 'writers': ['Urobuchi Gen', 'Type-Moon']}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[X] s1e  1 => s2e 14 air_date: 2012-04-06 language_rank: 0, title: "Bloody Battle on the Mion River"
[X] s1e  2 => s2e 15 air_date: 2012-04-06 language_rank: 0, title: "Golden Light"
[X] s1e  3 => s2e 16 air_date: 2012-04-22 language_rank: 0, title: "The End of Honor"
[X] s1e  4 => s2e 17 air_date: 2012-04-29 language_rank: 0, title: "The Eighth Contract"
[X] s1e  5 => s2e 18 air_date: 2012-05-06 language_rank: 0, title: "Distant Memories"
[X] s1e  6 => s2e 19 air_date: 2012-05-13 language_rank: 0, title: "Where Justice Dwells"
[X] s1e  7 => s2e 20 air_date: 2012-05-20 language_rank: 0, title: "The Assassin Returns"
[X] s1e  8 => s2e 21 air_date: 2012-05-27 language_rank: 0, title: "Knight on a Two-Wheeled Steed"
[X] s1e  9 => s2e 22 air_date: 2012-06-03 language_rank: 0, title: "All the Evil in the World"
[X] s1e 10 => s2e 23 air_date: 2012-06-10 language_rank: 0, title: "The Ocean at the End of the World"
[X] s1e 11 => s2e 24 air_date: 2012-06-17 language_rank: 0, title: "The Final Command Spell"
[X] s1e 12 => s2e 25 air_date: 2012-06-24 language_rank: 0, title: "Fate/Zero"
[ ] s0e  1 => s0e  0 epNumType: 2
[ ] s0e  2 => s0e  6 epNumType: 2
[ ] s0e  3 => s0e  7 epNumType: 2
...
```
Example of 'tvdb3':
```
=== Update ==================================================================================================================================================
id: tvdb3-275039, title: Pretty Guardian Sailor Moon Crystal, lang: en, force: True, movie: False
start: 2018-10-29 08:52:37,308817
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - tvdb_numbering: True
[+] AniDBid:  9306, TVDBid: 275039, defaulttvdbseason:  1, offset:   0, name: Bishoujo Senshi Sailor Moon Crystal
    - season: [ 1],           [ 2], range:      [ 15- 26], offset: -14, text: 
[+] AniDBid: 11665, TVDBid: 275039, defaulttvdbseason:  3, offset:   0, name: Bishoujo Senshi Sailor Moon Crystal Season III
             -----          ------
              9306          275039
mappingList: {'TVDB': {'s2e12': ('1', '26', '9306'), 's2e10': ('1', '24', '9306'), 's2e11': ('1', '25', '9306'), 's3': {'11665': '0'}, 's1': {'9306': '0'}, 's2e8': ('1', '22', '9306'), 's2e9': ('1', '23', '9306'), 's2e1': ('1', '15', '9306'), 's2e2': ('1', '16', '9306'), 's2e3': ('1', '17', '9306'), 's2e4': ('1', '18', '9306'), 's2e5': ('1', '19', '9306'), 's2e6': ('1', '20', '9306'), 's2e7': ('1', '21', '9306')}, 'season_map': {'9306': {'max': '2', 'min': '1'}, '11665': {'max': '3', 'min': '3'}}, 'defaulttvdbseason': '1'}
...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
AniDBid: 11665, url: http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11665
common.LoadFile() - file cached - CacheTime: 'Wed Oct 24 23:34:18 2018', Limit: 'Sun Nov  4 07:52:37 2018', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11665', Filename: 'AniDB/xml/11665.xml' file_valid: 'True'
[ ] 'title': Sailor Moon Crystal Season 3, original_title: Bishoujo Senshi Sailor Moon Crystal Season III, language_rank: 0
[ ] Roles (creators tag): {'producers': ['Kobayashi Yuuji'], 'directors': ['Kon Chiaki', 'Takahashi Akira', 'Yamaoka Naoko'], 'writers': ['Takeuchi Naoko']}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[X] s1e  1 => s3e 27 air_date: 2016-03-06 language_rank: 0, title: "Infinity 1: Premonition - First Part"
[X] s1e  2 => s3e 28 air_date: 2016-04-11 language_rank: 0, title: "Infinity 1: Premonition - Second Part"
[X] s1e  3 => s3e 29 air_date: 2016-04-18 language_rank: 0, title: "Infinity 2: Ripples"
[X] s1e  4 => s3e 30 air_date: 2016-04-25 language_rank: 0, title: "Infinity 3: Two New Soldiers"
[X] s1e  5 => s3e 31 air_date: 2016-05-02 language_rank: 0, title: "Infinity 4: Haruka Tenoh, Michiru Kaioh - Sailor Uranus, Sailor Neptune"
[X] s1e  6 => s3e 32 air_date: 2016-05-09 language_rank: 0, title: "Infinity 5: Setsuna Meioh - Sailor Pluto"
[X] s1e  7 => s3e 33 air_date: 2016-05-16 language_rank: 0, title: "Infinity 6: Three Guardians"
[X] s1e  8 => s3e 34 air_date: 2016-05-23 language_rank: 0, title: "Infinity 7: Transformation - Super Sailor Moon"
[X] s1e  9 => s3e 35 air_date: 2016-05-30 language_rank: 0, title: "Infinity 8: "Infinite Labyrinth" 1"
[X] s1e 10 => s3e 36 air_date: 2016-06-06 language_rank: 0, title: "Infinity 9: "Infinite Labyrinth" 2"
[X] s1e 11 => s3e 37 air_date: 2016-06-13 language_rank: 0, title: "Infinity 10: Infinite - Upper Atmosphere"
[X] s1e 12 => s3e 38 air_date: 2016-06-20 language_rank: 0, title: "Infinity 11: Infinite - Judge"
[X] s1e 13 => s3e 39 air_date: 2016-06-27 language_rank: 0, title: "Infinity 12: Infinite - Journey"
[ ] s0e101 => s0e  0 epNumType: 3
[ ] s0e102 => s0e  0 epNumType: 3
[ ] s0e103 => s0e  0 epNumType: 3
...
```
Example of 'tvdb3' & 'defaulttvdbseason'=='a':
```
=== Update ==================================================================================================================================================
id: tvdb3-74796, title: Bleach, lang: en, force: True, movie: False
start: 2018-10-29 08:56:10,801122
-------------------------------------------------------------------------------------------------------------------------------------------------------------
AnimeLists.GetMetadata() - tvdb_numbering: True
[+] AniDBid:  2369, TVDBid:  74796, defaulttvdbseason:  a, offset:   0, name: Bleach
    - season: [ 0],           [ 0], range:      [000-000], offset:   0, text: 1-0;2-0;3-2;4-99
[+] AniDBid:  4515, TVDBid:  74796, defaulttvdbseason:  0, offset:   0, name: Gekijouban Bleach: Memories of Nobody
    - season: [ 1],           [ 0], range:      [000-000], offset:   0, text: 1-3
[+] AniDBid:  5352, TVDBid:  74796, defaulttvdbseason:  0, offset:   0, name: Gekijouban Bleach: The DiamondDust Rebellion Mou Hitotsu no Hyourinmaru
    - season: [ 1],           [ 0], range:      [000-000], offset:   0, text: 1-4
[+] AniDBid:  6041, TVDBid:  74796, defaulttvdbseason:  0, offset:   0, name: Gekijouban Bleach: Fade to Black Kimi no Na o Yobu
    - season: [ 1],           [ 0], range:      [000-000], offset:   0, text: 1-5
[+] AniDBid:  7666, TVDBid:  74796, defaulttvdbseason:  0, offset:   0, name: Gekijouban Bleach: Jigoku-hen
    - season: [ 1],           [ 0], range:      [000-000], offset:   0, text: 1-6
             -----          ------
              2369           74796
mappingList: {'TVDB': {'s0e0': ('0', '1', '2369'), 's0e6': ('1', '1', '7666'), 's0e4': ('1', '1', '5352'), 's0e5': ('1', '1', '6041'), 's0e2': ('0', '3', '2369'), 's0e3': ('1', '1', '4515'), 's-1': {'6041': '0', '5352': '0', '7666': '0', '4515': '0'}, 's0e99': ('0', '4', '2369'), 'sa': {'2369': '0'}}, 'season_map': {'7666': {'max': '0', 'min': '0'}, '6041': {'max': '0', 'min': '0'}, '5352': {'max': '0', 'min': '0'}, '2369': {'max': 'a', 'min': 'a'}, '4515': {'max': '0', 'min': '0'}}, 'defaulttvdbseason': 'a'}
...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[X] s1e  1 => s1e  1 air_date: 2004-10-05 language_rank: 0, title: "A Shinigami is Born!"
[X] s1e  2 => s1e  2 air_date: 2004-10-12 language_rank: 0, title: "Pay or Play"
[X] s1e  3 => s1e  3 air_date: 2004-10-19 language_rank: 0, title: "Sibling Rivalry"
[X] s1e  4 => s1e  4 air_date: 2004-10-26 language_rank: 0, title: "And Your Bird Can Speak"
[X] s1e  5 => s1e  5 air_date: 2004-11-02 language_rank: 0, title: "Beat the Invisible Enemy!"
[X] s1e  6 => s1e  6 air_date: 2004-11-09 language_rank: 0, title: "Fight to the Death! Ichigo vs. Ichigo"
[X] s1e  7 => s1e  7 air_date: 2004-11-16 language_rank: 0, title: "Greetings from a Stuffed Toy"
[X] s1e  8 => s1e  8 air_date: 2004-11-23 language_rank: 0, title: "June 17, a Memory of Rain"
[X] s1e  9 => s1e  9 air_date: 2004-11-30 language_rank: 0, title: "Unbeatable Enemy"
[X] s1e 10 => s1e 10 air_date: 2004-12-07 language_rank: 0, title: "Assault on Trip at Sacred Ground!"
[X] s1e 11 => s1e 11 air_date: 2004-12-14 language_rank: 0, title: "The Legendary Quincy"
...
```

### CODE REVIEW

**Comment by ZeroQI** [comment]
Thanks for all these fixes and improvement
All look good to me

**Comment by EndOfLine369** [comment]
Np, I think i'm almost if not as far as I can enhance/fix.
Don't see any more problems I can easily see in the logs.

**Comment by ZeroQI** [comment]
I like the code simplification. It's always easy to make it complicated and complicated to make it easy...
I really like the neat logging. Makes T/S way easier now.
If you need any information let me know but I am not 100% sure I understand the mechanics of tvdb3/4 fixes introduced. You are better at python than I am, but i did bring it pretty far on my own, but really appreciate the help. It is way better now.

On an unrelated note:
- walls of the house I am getting build in France are up for ground floor
- my car was stolen the 13th but found back but Cat C write-off due to cost :/ Found donor car for parts but depends on how much the insurance want to deduct from the pay off for its butchered remains...
- Should have more time once the car issue is resolved. Will fix the optimized files issue on scanner Saturday.
- Lambda code line 720 you can query with this variable the season xml, it looks like this:
```
<?xml version='1.0' encoding='utf8'?>
<Directory ratingKey="1374" key="/library/metadata/1374/children" parentRatingKey="1373" type="season" title="Season 1" parentKey="/library/metadata/1373" parentTitle="Naruto" summary="" index="1" parentIndex="1" thumb="/library/metadata/1374/thumb/1540147417" art="/library/metadata/1373/art/1540147417" parentThumb="/library/metadata/1373/thumb/1540147417" parentTheme="/library/metadata/1373/theme/1540147417" addedAt="1521247672" updatedAt="1540147417">
</Directory>
```
rest is to update fields not in metadata.xxxx
https://github.com/defract/TMDB-Collection-Data-Retriever/blob/master/collection_updater.py line 211  upload back movie posters for collections for example
in Lambda code, PLEX_UPLOAD_TEXT allow to upload back collection summary even though it cannot be reached to my knowledge by metadata.xxx

**Comment by ZeroQI** [comment]
Please attach agent logs will have a look

**Comment by EndOfLine369** [comment]
Updated logging and wait logic https://github.com/ZeroQI/Hama.bundle/commit/e9910aba3e3b647aa48e56b816f1c343887397e2 to even make sure multiple were not run at the same time.
But still got a ban. Almost at the exact same point in the library each time. (6sec waits)
```
2018-11-04 03:02:21,717 - 7fce3ae6b700 - Lock acquired: 'anidb'
2018-11-04 03:02:21,723 - 7fce3ae6b700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10931'
2018-11-04 03:02:22,271 - 7fce3ae6b700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10931'
2018-11-04 03:02:28,278 - 7fce3ae6b700 - Lock released: 'anidb'
2018-11-04 03:02:32,723 - 7fce39cdf700 - Lock acquired: 'anidb'
2018-11-04 03:02:32,727 - 7fce39cdf700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13060'
2018-11-04 03:02:33,177 - 7fce39cdf700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13060'
2018-11-04 03:02:39,182 - 7fce39cdf700 - Lock released: 'anidb'
2018-11-04 03:02:39,421 - 7fce39cdf700 - Lock acquired: 'anidb'
2018-11-04 03:02:41,052 - 7fce39cdf700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=513'
2018-11-04 03:02:41,673 - 7fce39cdf700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=513'
2018-11-04 03:02:47,680 - 7fce39cdf700 - Lock released: 'anidb'
2018-11-04 03:02:47,964 - 7fce39cdf700 - Lock acquired: 'anidb'
2018-11-04 03:02:48,018 - 7fce39cdf700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=514'
2018-11-04 03:02:48,719 - 7fce39cdf700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=514'
2018-11-04 03:02:54,724 - 7fce39cdf700 - Lock released: 'anidb'
2018-11-04 03:02:54,981 - 7fce39cdf700 - Lock acquired: 'anidb'
2018-11-04 03:02:57,105 - 7fce39cdf700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=102'
2018-11-04 03:02:57,580 - 7fce39cdf700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=102'
2018-11-04 03:03:03,583 - 7fce39cdf700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-04 03:03:03,584 - 7fce39cdf700 - Lock released: 'anidb'
2018-11-04 03:03:03,935 - 7fce39cdf700 - Lock acquired: 'anidb'
2018-11-04 03:03:04,056 - 7fce39cdf700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=12140'
2018-11-04 03:03:04,390 - 7fce39cdf700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=12140'
2018-11-04 03:03:10,392 - 7fce39cdf700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-04 03:03:10,393 - 7fce39cdf700 - Lock released: 'anidb'
```
At the point where i'm now confident in the logic with the enhanced logging, will now start increasing the wait to see what it takes to not get banned.

**Comment by ZeroQI** [comment]
It is possible the wait time is OK but the same XML got downloaded 3+ times the same day which would cause a ban too but I would use local cache date to not download twice normally+Plex cache...

Is it the same series that give an instant ban maybe?

I think I recall an entry making a ban volontarilly for tests...

**Comment by EndOfLine369** [comment]
Only downloaded once. 24hr ban made this a guarantee. And as testing the ban, i'm clearing the Plex cache and deleting the local xml files.

Will let you know in 24hrs once ban is lifted again if happens on same series. Also increasing wait to 10sec in the next test.

**Comment by EndOfLine369** [comment]
Banned again. Even with 10sec.
Difference series but around the same area. Feels like a ban for requesting too much info......which is crazy but those guys are crazy on nonsensical bans....
```
2018-11-04 22:26:49,717 - 7f12a3fff700 - Lock acquired: 'anidb'
2018-11-04 22:26:49,738 - 7f12a3fff700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10931'
2018-11-04 22:26:50,217 - 7f12a3fff700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10931'
2018-11-04 22:27:00,227 - 7f12a3fff700 - Lock released: 'anidb'
2018-11-04 22:27:00,228 - 7f12d1668700 - Lock acquired: 'anidb'
2018-11-04 22:27:00,250 - 7f12d1668700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=6032'
2018-11-04 22:27:00,892 - 7f12d1668700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=6032'
2018-11-04 22:27:10,901 - 7f12d1668700 - Lock released: 'anidb'
2018-11-04 22:27:10,902 - 7f12d0f4c700 - Lock acquired: 'anidb'
2018-11-04 22:27:10,926 - 7f12d0f4c700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=102'
2018-11-04 22:27:11,741 - 7f12d0f4c700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=102'
2018-11-04 22:27:21,752 - 7f12d0f4c700 - Lock released: 'anidb'
2018-11-04 22:27:22,440 - 7f12d0f4c700 - Lock acquired: 'anidb'
2018-11-04 22:27:22,445 - 7f12d0f4c700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=12140'
2018-11-04 22:27:23,109 - 7f12d0f4c700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=12140'
2018-11-04 22:27:33,120 - 7f12d0f4c700 - Lock released: 'anidb'
2018-11-04 22:27:33,533 - 7f12d1668700 - Lock acquired: 'anidb'
2018-11-04 22:27:33,556 - 7f12d1668700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=131'
2018-11-04 22:27:34,073 - 7f12d1668700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=131'
2018-11-04 22:27:44,084 - 7f12d1668700 - Lock released: 'anidb'
2018-11-04 22:27:44,381 - 7f12a3fff700 - Lock acquired: 'anidb'
2018-11-04 22:27:44,386 - 7f12a3fff700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=7599'
2018-11-04 22:27:45,285 - 7f12a3fff700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=7599'
2018-11-04 22:27:55,289 - 7f12a3fff700 - Lock released: 'anidb'
2018-11-04 22:27:55,599 - 7f12a3fff700 - Lock acquired: 'anidb'
2018-11-04 22:27:55,651 - 7f12a3fff700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5975'
2018-11-04 22:27:56,009 - 7f12a3fff700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5975'
2018-11-04 22:28:06,018 - 7f12a3fff700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-04 22:28:06,019 - 7f12a3fff700 - Lock released: 'anidb'
2018-11-04 22:28:06,430 - 7f12a3fff700 - Lock acquired: 'anidb'
2018-11-04 22:28:06,446 - 7f12a3fff700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8694'
2018-11-04 22:28:06,804 - 7f12a3fff700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8694'
2018-11-04 22:28:16,815 - 7f12a3fff700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-04 22:28:16,816 - 7f12a3fff700 - Lock released: 'anidb'
```

**Comment by EndOfLine369** [comment]
From the two noted above:
* Ban after 134 series
* Ban after 137 series

**Pull request merged**
