### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by EndOfLine369**
Hi @ZeroQI,

Please help review.

### CODE REVIEW

**Comment by EndOfLine369** [comment]
Hi @sven-7, key error as you didn't get required info from AniDB for relation_map which is expected and a wanted crash.

If you had just gotten banned, you would of had an xml from before. You were banned before this as there is no preexisting xml to load on a ban no matter the cache age. It was just not as visible to that fact if you didn't look at the individual log files. One of the updates here is to enhance logging to clearly state when you're banned.

**Comment by EndOfLine369** [comment]
Without the relation info, it doesn't know how to adjust the tvdb info. so you really don't want incorrect meta to load from incorrectly placed tvdb info. you really want no info loaded till AniDB info is available.

**Comment by EndOfLine369** [comment]
What your seeing now is what unfortunately has been the bad norm of AniDB bans.

**Comment by sven-7** [comment]
Makes sense to me. Best/only option is to wait out the ban?

**Comment by EndOfLine369** [comment]
Yes. I suspect you've only really loaded ~100 if your entries with AniDB info. And others have just always been TVDB info as by time it gets to them, your banned from AniDB.

**Comment by sven-7** [comment]
Bummer. Guess I eventually have to do a manual update on those ones that aren't updated regularly to make sure I haven't been missing things this whole time. Thanks for the info. Haven't had any other issues.

**Comment by EndOfLine369** [comment]
How many xmls do you actually have in 'Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\xml' ?

**Comment by sven-7** [comment]
I have the right amount - about 490. All dated 11/5 or newer, from when I did my full refresh.

**Comment by EndOfLine369** [comment]
Lucky, i've been having to manually refresh ~70 at a time with a 1hr break between to not get banned. Could be your comp might not be that fast and is delayed enough to not be requesting too many too quickly....?

From my testing:
* Banned after 134 series (w/6sec between requests) - took 27min
* Banned after 137 series (w/10sec between requests) - took 28min
* No ban in 58 series (w/10sec between requests) - took 18min

Looks like if I stay at less than ~80 xmls in one go, I don't get banned.

**Comment by sven-7** [comment]
Interesting.  That's possible? Processor wise, I shouldn't be, running an i7 4.2GHz.  I do route my traffic through a VPN tunnel, so it's possible I'm getting slowed up there. Happy to provide specs if that gives context.  

I'm not familiar with how Plex or the Agent handles it when doing a "Refresh All Metadata".  I do clean out the xml folders and \Plug-in Support\Caches before doing it tho.

**Comment by EndOfLine369** [comment]
Added in a log statement, do you mind pulling that update and rerunning the one that currently crashes from the ban.

**Comment by EndOfLine369** [comment]
Otherwise i'll test later when I get to my eventual ban ☹️

**Comment by EndOfLine369** [comment]
Q: since you clear the xmls. what is the actual file timstamp of the oldest and newest xml for those ~490?

**Comment by sven-7** [comment]
Sure thing - I'll give it a go.

The full refresh started at 11/5 at 11:48a and finished up around 2:10p. Only a few series have been updated since then.

**Comment by sven-7** [comment]
Well, just for fun, I kicked off a full refresh.  Will report back tomorrow with how it goes.

**Comment by EndOfLine369** [comment]
Well, crap. hit the ban faster than I wanted...
Do see the new log entry though.
```
2018-11-07 21:37:52,991 - 7fa6e46af700 - Lock acquired: 'anidb'
2018-11-07 21:37:53,014 - 7fa6e46af700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=202'
2018-11-07 21:37:53,369 - 7fa6e46af700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=202'
2018-11-07 21:37:59,376 - 7fa6e46af700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-07 21:37:59,377 - 7fa6e46af700 - Lock released: 'anidb'
2018-11-07 21:37:59,378 - 7fa6e46af700 - No preexisting file 'AniDB/xml/202.xml' to load
2018-11-07 21:37:59,756 - 7fa6e46af700 - Lock acquired: 'anidb'
2018-11-07 21:37:59,773 - 7fa6e46af700 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=326'
2018-11-07 21:38:00,185 - 7fa6e46af700 - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=326'
2018-11-07 21:38:06,187 - 7fa6e46af700 - Banned from 'anidb': <error code="500">banned</error>
2018-11-07 21:38:06,187 - 7fa6e46af700 - Lock released: 'anidb'
2018-11-07 21:38:06,189 - 7fa6e46af700 - No preexisting file 'AniDB/xml/326.xml' to load
```

**Comment by sven-7** [comment]
I started 80 min ago, last xml 39 minutes in, with 225 xml. Getting this:

```
2018-11-07 23:53:01,392 (3de8) :  DEBUG (sandbox:19) - Lock acquired: 'anidb'
2018-11-07 23:53:01,440 (3de8) :  DEBUG (networking:166) - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8550'
2018-11-07 23:53:01,743 (3de8) :  DEBUG (sandbox:19) - Completed 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8550'
2018-11-07 23:53:07,752 (3de8) :  DEBUG (sandbox:19) - Banned from 'anidb': <error code="500">banned</error>
2018-11-07 23:53:07,753 (3de8) :  DEBUG (sandbox:19) - Lock released: 'anidb'
2018-11-07 23:53:07,755 (3de8) :  DEBUG (sandbox:19) - No preexisting file 'AniDB\xml\8550.xml' to load
```

**Comment by EndOfLine369** [comment]
Thanks for the simplification. Committed.

**Comment by EndOfLine369** [comment]
Re AniDB, no. Looks like AniDB is just making itself set to ridiculously low thresholds on ban requirements now. Can't do more than 50-60 if you don't want an eventual ban. Otherwise, its a try as fast/long as you can to get as many as you can till you get banned. You would potentially have to set it to 30-60sec....maybe.... Biggest problem is no definition on what will get you banned.

**Comment by EndOfLine369** [comment]
Was just frequency and number of times of same request. Not the case now and documentation not updated on what has changed. They seem to have added not liking you getting too many or for trying for too long from what I can tell.
https://wiki.anidb.net/w/HTTP_API_Definition#Flooding_and_Caching

**Comment by EndOfLine369** [comment]
Basically a leeching overreaction.

**Comment by ZeroQI** [comment]
Yeah they do that but to happen with the file cache you would have to delete it and plex cache and recreate the library though...
Really like the Dict and SaveDict functions, created them mysels and they simplify coding so much... The savedict add to a list if the object to save is a list, and Dict allow to set default value, avoiding the need for tests...

**Pull request merged**
