### PR TITLE
Enhance error logs to be fully maintained

### PR DESCRIPTION
**Pull request by EndOfLine369**

### CODE REVIEW

**Comment by MagellanSails** [comment]
Any reason you replaced the "," with "|" in the log statements? Not a big deal, just wondering if it was a preference thing or if the commas were causing problems.

**Comment by EndOfLine369** [comment]
By making the separator a pipe "|", it will not require users to clear out their log files. It will do it automatically for them as it was not used previously and parsing of the logs requires the pipe to be present for key/value dict separation. So one less step to make sure people do.

It also makes the text a lot more readable in determining blocks of text in my opinion. Especially when there is a lot of information. It makes it look as close to a column line.
image

**Comment by EndOfLine369** [comment]
Was tempted to actually change the logs into tables instead of </br> separated lines but that would add more white space in line separation so didn't. As I wanted to keep the data compressed as much as I can. Especially when most of my files have many many lines.

**Comment by sven-7** [comment]
Have been testing this today.  I set a full refresh to run about 5 hours ago and it's still running -- it seems a lot longer.  It's only processed about 110 shows in that time span.  I'm not sure if the previous full refreshes had gone faster, but it now seems to be quite slow.  I don't see this as a problem, because many people won't full refresh all the time, but just something to make note of.

Once it's done, I'll give some more feedback.

**Comment by sven-7** [comment]
Actually - I see the cause.  Looks like the lock files are causing it to pause.


[com.plexapp.agents.hama.log.zip](https://github.com/ZeroQI/Hama.bundle/files/294083/com.plexapp.agents.hama.log.zip)

**Comment by EndOfLine369** [comment]
Looks like your comp could of had an issue earlier where it would not delete the lock files by the os after updating the contents. Or maybe the refresh was killed in the middle so hama could not get to delete them. I would need all your hama logs from the start of your refresh to see if there was anything in them. My Guess would be that if you looked at your Data files dir now, you will have lock files sticking around with old timestamps?

I will need to see what to do about these lock files. They are needed as hama runs multiple refreshes at the same time so there were multiple instances where the logs lost data as one instance read while the file was being written to so it only read/updated partially written data.

No issues were seen with these locks:
```
2016-06-01 14:15:21,164 (1610) :  DEBUG (logkit:13) - 'Missing Specials.htm.lock' Clear.
2016-06-01 14:15:21,180 (1610) :  DEBUG (logkit:13) - 'Missing Episodes.htm.lock' Clear.
```
The other locks seem to have had issues:
```
2016-06-01 14:15:20,680 (e00) :  DEBUG (logkit:13) - 'anime-list studio logos.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:16:26,075 (1610) :  DEBUG (logkit:13) - 'anime-list tvdbid missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:20:12,823 (101c) :  DEBUG (logkit:13) - 'anime-list anidbid missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:15:20,821 (16c4) :  DEBUG (logkit:13) - 'AniDB summaries missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:15:56,670 (1610) :  DEBUG (logkit:13) - 'AniDB posters missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:15:56,311 (16c4) :  DEBUG (logkit:13) - 'Plex themes missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:17:23,516 (16c4) :  DEBUG (logkit:13) - 'TVDB posters missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:17:23,874 (1610) :  DEBUG (logkit:13) - 'TVDB season posters missing.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:20:13,154 (1610) :  DEBUG (logkit:13) - 'Missing Episode Summaries.htm.lock' Exists. Sleeping 1sec for lock to disappear.
2016-06-01 14:20:32,066 (16c4) :  DEBUG (logkit:13) - 'Missing Special Summaries.htm.lock' Exists. Sleeping 1sec for lock to disappear.
```

**Comment by sven-7** [comment]
I'm not very familiar with lock files.  The refresh is still going now, about 14 hours later.

Here are all my logs thus far.

[newlogs.zip](https://github.com/ZeroQI/Hama.bundle/files/294760/newlogs.zip)
screen shot 2016-06-01 at 11 16 41 pm

**Comment by EndOfLine369** [comment]
Ok, i'm too use to multiple processes needing to talk to each other thus an external lock file. But this is actually a multi threaded single process. So...

- Moved locks into an internal shared variable. Will remove risk of os/disk update issues @sven-7 had.
- Reduced the waiting timeout to 10sec
- Added in a override to the lock when the lock is older than timeout*2

**Comment by EndOfLine369** [comment]
@sven-7, you can try to delete those lock files to see if your refresh will move on. Otherwise you might have to restart plex to stop the refresh.

**Comment by EndOfLine369** [comment]
Also, thanks for testing. Sry it didn't go well. :frowning:

**Comment by sven-7** [comment]
Hey, no worries at all @EndOfLine369!  That's why we test, right? :wink:

I won't be able to test until later today, but I'll give it another go.

**Comment by sven-7** [comment]
I added the new HAMA, but everything seems to be hanging up now.  I added a single episode and the scanner is stuck.  New logs do not seem to have been created either.

**Comment by MagellanSails** [comment]
I tried the latest from Master last night and that worked fine, but I will pull this tonight and give it a go. Try and see if the issue is something special in @sven-7 's library or if it is happening across the board

**Comment by sven-7** [comment]
I added a single episode and it's been scanning for an hour now.  I killed it -- logs attached. I started with clean logs.  A log for HAMA didn't even generate.


[logs 0602.zip](https://github.com/ZeroQI/Hama.bundle/files/296426/logs.0602.zip)

**Comment by MagellanSails** [comment]
Just pulled this latest from this branch, [minor fix of missed prev updates](https://github.com/ZeroQI/Hama.bundle/pull/48/commits/ec7cd902f5ecb26b9a5c1682bf34d771541b6274), and did a full refresh on my series. My library is relatively smaller (79 shows currently), but it finished in ~3 minutes.

Seemed to work really well. The only issue I saw was with the Missing Specials for HxH 2011. There are the right number of items in the array (I don't have either movie), but the _s0e1_ and _s0e2_ are missing.

No lock issues!
hxh missing specials

**Comment by sven-7** [comment]
Still no luck.  Scanner goes on indefinitely. No HAMA logs are being created in '\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems'


[Logs.zip](https://github.com/ZeroQI/Hama.bundle/files/298411/Logs.zip)

**Comment by EndOfLine369** [comment]
@MagellanSails, glad it worked well :smile: 
I don't seem to have that issue with HunterXHunter. Looks like your also using a tvdb id as i am for mapping. I'm using "[tvdb3-252322]" but all tvdb ids use the same piece of code for looking at the missing episodes.

image
Please try a refresh of just that series in Plex to see if it was just an issue in your load at that time.

@sven-7, Good to hear you got your Plex back into a working order. I suspect you might have not pulled the last commit code which was done as I accidentally missed some updates in my second commit to change from the lock files. Here is a link to the latest. 
https://raw.githubusercontent.com/ZeroQI/Hama.bundle/ec7cd902f5ecb26b9a5c1682bf34d771541b6274/Contents/Code/__init__.py

**Comment by sven-7** [comment]
I think at some point, I had your second commit.  But I suspected that yesterday as well and made sure I had the latest.  It scans, it downloads metadata, but nothing is written to the htm logs.  I just did a refresh and none of the logs have been updated.  Is there any place in the HAMA logs where it would indicate if it successfully wrote to the htm log or not?

**Comment by EndOfLine369** [comment]
It would be in the hama logs 'com.plexapp.agents.hama.log'. This should be printed at the end of each refresh showing it got the locks and updated the files.
```
{'Rating': '8.5', 'Overview': 'East Blue in crisis? The news hits the Straw Hat crew  along their journey. With their hometowns facing a pinch, Luffy and his friends put their adventures on hold and decide to head back to East Blue, when suddenly a mysterious flying pirate ship appears out of the sky.', 'Writer': '', 'filename': 'episodes/81797/2252421.jpg', 'Director': '', 'FirstAired': '2009-12-12', 'EpisodeName': 'Strong World'}}'
2016-06-06 04:51:49,707 (-bc3e470) :  DEBUG (__init__:621) - Locked 'anime-list anidbid missing' [True, 1465206709]
2016-06-06 04:51:49,709 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'anime-list anidbid missing' [False, 0]
2016-06-06 04:51:49,710 (-bc3e470) :  DEBUG (__init__:621) - Locked 'anime-list studio logos' [True, 1465206709]
2016-06-06 04:51:49,729 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'anime-list studio logos' [False, 0]
2016-06-06 04:51:49,729 (-bc3e470) :  DEBUG (__init__:621) - Locked 'AniDB summaries missing' [True, 1465206709]
2016-06-06 04:51:49,743 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'AniDB summaries missing' [False, 0]
2016-06-06 04:51:49,743 (-bc3e470) :  DEBUG (__init__:621) - Locked 'Plex themes missing' [True, 1465206709]
2016-06-06 04:51:49,746 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'Plex themes missing' [False, 0]
2016-06-06 04:51:49,747 (-bc3e470) :  DEBUG (__init__:621) - Locked 'TVDB posters missing' [True, 1465206709]
2016-06-06 04:51:49,758 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'TVDB posters missing' [False, 0]
2016-06-06 04:51:49,759 (-bc3e470) :  DEBUG (__init__:621) - Locked 'Missing Specials' [True, 1465206709]
2016-06-06 04:51:49,776 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'Missing Specials' [False, 0]
2016-06-06 04:51:49,777 (-bc3e470) :  DEBUG (__init__:621) - Locked 'Missing Episodes' [True, 1465206709]
2016-06-06 04:51:49,801 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'Missing Episodes' [False, 0]
2016-06-06 04:51:49,802 (-bc3e470) :  DEBUG (__init__:621) - Locked 'AniDB posters missing' [True, 1465206709]
2016-06-06 04:51:49,803 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'AniDB posters missing' [False, 0]
2016-06-06 04:51:49,804 (-bc3e470) :  DEBUG (__init__:621) - Locked 'anime-list tvdbid missing' [True, 1465206709]
2016-06-06 04:51:49,813 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'anime-list tvdbid missing' [False, 0]
2016-06-06 04:51:49,814 (-bc3e470) :  DEBUG (__init__:621) - Locked 'TVDB season posters missing' [True, 1465206709]
2016-06-06 04:51:49,820 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'TVDB season posters missing' [False, 0]
2016-06-06 04:51:49,821 (-bc3e470) :  DEBUG (__init__:621) - Locked 'Missing Special Summaries' [True, 1465206709]
2016-06-06 04:51:49,837 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'Missing Special Summaries' [False, 0]
2016-06-06 04:51:49,837 (-bc3e470) :  DEBUG (__init__:621) - Locked 'Missing Episode Summaries' [True, 1465206709]
2016-06-06 04:51:49,856 (-bc3e470) :  DEBUG (__init__:624) - Unlocked 'Missing Episode Summaries' [False, 0]
2016-06-06 04:51:49,857 (-bc3e470) :  DEBUG (__init__:625) - --- Update end -------------------------------------------------------------------------------------------------
```
Have you also tried deleting the htm files before a refresh for the agent to create from scratch? It could be from your os/disk original issues that the files got messed up or the OS is keeping some lock on the file.

**Comment by sven-7** [comment]
Yeah, I delete them before I do a refresh each time.  So I'm at a loss... if it's the latter, I'm not sure what to do.

**Comment by sven-7** [comment]
Here is my log:

[hama log.zip](https://github.com/ZeroQI/Hama.bundle/files/301083/hama.log.zip)

**Comment by MagellanSails** [comment]
@sven-7 If it really turned out to be an issue with Windows keeping a lock on a non-existent file, then you could try killing explorer.exe or the plex process trees, or just restart your machine.

**Comment by EndOfLine369** [comment]
It looks clear in that log
```
2016-06-06 14:07:25,210 (580) :  CRITICAL (core:574) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb3-275039?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-5089475\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\Sven\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 814, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  False )
  File "C:\Users\Sven\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 621, in Update
    if key4 in log_array.keys(): del(log_array[key4])
ValueError: Invalid format string
```

Can you please provide the file list for your "B:\Anime Series\Sailor Moon Crystal".
It also looks like that is the only one trying to be refreshed in that log. Can you please refresh another series to see if the same error shows up in the agent log.

**Comment by EndOfLine369** [comment]
please also provide the \_\_init\_\_.py file you have

**Comment by EndOfLine369** [comment]
Have you also tried to restart your system post the initial testing issues? If not, please do to eliminate that being the cause of the above error.

**Comment by sven-7** [comment]
Have restarted the system, but will try killing the plex process as well.

[__init__.zip](https://github.com/ZeroQI/Hama.bundle/files/301092/__init__.zip)

**Comment by sven-7** [comment]
```
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 1 - Act 1. Usagi ~Sailor Moon~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 10 - Act 10. Moon.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 11 - Act 11. Reunion ~Endymion~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 12 - Act 12. Enemy ~Queen Metalia~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 13 - Act 13. Final Battle ~Reincarnation~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 14 - Act 14. Conclusion and Commencement ~Petite Étrangère~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 15 - Act 15. Infiltration ~Sailor Mars~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 16 - Act 16. Abduction ~Sailor Mercury~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 17 - Act 17. Secrecy ~Sailor Jupiter~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 18 - Act 18. Invasion ~Sailor Venus~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 19 - Act 19. Time Warp ~Sailor Pluto~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 2 - Act 2. Ami ~Sailor Mercury~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 20 - Act 20. Crystal Tokyo ~King Endymion~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 21 - Act 21. Complication ~Nemesis~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 22 - Act 22. Hidden Agenda ~Nemesis~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 23 - Act 23. Covert Maneuvers ~Wiseman~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 24 - Act 24. Attack ~Black Lady~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 25 - Act 25. Showdown ~Death Phantom~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 26 - Act 26. Replay ~Never Ending~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 27 - Act 27. Infinity 1 - Premonition (Part 1).mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 28 - Act 27. Infinity 1 - Premonition (Part 2).mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 29 - Act 28. Infinity 2 - Ripples.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 3 - Act 3. Rei ~Sailor Mars~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 30 - Act 29. Infinity 3 - Two New Soldiers.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 31 - Act 30. Infinity 4 - Haruka Tenoh, Michiru Kaioh ~Sailor Uranus, Sailor Neptune~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 32 - Act 31. Infinity 5 - Setsuna Meiou ~Sailor Pluto~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 33 - Act 32. Infinity 6 - Three Guardians.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 34 - Act 33. Infinity 7 - Transformation ~Super Sailor Moon~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 4 - Act 4. Masquerade ~Dance Party~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 5 - Act 5. Makoto ~Sailor Jupiter~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 6 - Act 6. Tuxedo Mask.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 7 - Act 7. Mamoru Chiba ~Tuxedo Mask~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 8 - Act 8. Minako ~Sailor V~.mkv
B:\Anime Series\Sailor Moon Crystal\Sailor Moon Crystal - 9 - Act 9. Serenity ~Princess~.mkv

```

**Comment by EndOfLine369** [comment]
I am unable to replicate. No issues seen.
```
[t1]# ls Sailor\ Moon\ Crystal/
Sailor Moon Crystal - 1 - Act 1. Usagi ~Sailor Moon~.mkv
Sailor Moon Crystal - 10 - Act 10. Moon.mkv
Sailor Moon Crystal - 11 - Act 11. Reunion ~Endymion~.mkv
Sailor Moon Crystal - 12 - Act 12. Enemy ~Queen Metalia~.mkv
Sailor Moon Crystal - 13 - Act 13. Final Battle ~Reincarnation~.mkv
Sailor Moon Crystal - 14 - Act 14. Conclusion and Commencement ~Petite Étrangère~.mkv
Sailor Moon Crystal - 15 - Act 15. Infiltration ~Sailor Mars~.mkv
Sailor Moon Crystal - 16 - Act 16. Abduction ~Sailor Mercury~.mkv
Sailor Moon Crystal - 17 - Act 17. Secrecy ~Sailor Jupiter~.mkv
Sailor Moon Crystal - 18 - Act 18. Invasion ~Sailor Venus~.mkv
Sailor Moon Crystal - 19 - Act 19. Time Warp ~Sailor Pluto~.mkv
Sailor Moon Crystal - 2 - Act 2. Ami ~Sailor Mercury~.mkv
Sailor Moon Crystal - 20 - Act 20. Crystal Tokyo ~King Endymion~.mkv
Sailor Moon Crystal - 21 - Act 21. Complication ~Nemesis~.mkv
Sailor Moon Crystal - 22 - Act 22. Hidden Agenda ~Nemesis~.mkv
Sailor Moon Crystal - 23 - Act 23. Covert Maneuvers ~Wiseman~.mkv
Sailor Moon Crystal - 24 - Act 24. Attack ~Black Lady~.mkv
Sailor Moon Crystal - 25 - Act 25. Showdown ~Death Phantom~.mkv
Sailor Moon Crystal - 26 - Act 26. Replay ~Never Ending~.mkv
Sailor Moon Crystal - 27 - Act 27. Infinity 1 - Premonition (Part 1).mkv
Sailor Moon Crystal - 28 - Act 27. Infinity 1 - Premonition (Part 2).mkv
Sailor Moon Crystal - 29 - Act 28. Infinity 2 - Ripples.mkv
Sailor Moon Crystal - 3 - Act 3. Rei ~Sailor Mars~.mkv
Sailor Moon Crystal - 30 - Act 29. Infinity 3 - Two New Soldiers.mkv
Sailor Moon Crystal - 31 - Act 30. Infinity 4 - Haruka Tenoh, Michiru Kaioh ~Sailor Uranus, Sailor Neptune~.mkv
Sailor Moon Crystal - 32 - Act 31. Infinity 5 - Setsuna Meiou ~Sailor Pluto~.mkv
Sailor Moon Crystal - 33 - Act 32. Infinity 6 - Three Guardians.mkv
Sailor Moon Crystal - 34 - Act 33. Infinity 7 - Transformation ~Super Sailor Moon~.mkv
Sailor Moon Crystal - 35 - Act 34. Infinity 8 - Infinite Labyrinth 1.mkv
Sailor Moon Crystal - 36 - Act 35. Infinity 9 - Infinite Labyrinth 2.mkv
Sailor Moon Crystal - 4 - Act 4. Masquerade ~Dance Party~.mkv
Sailor Moon Crystal - 5 - Act 5. Makoto ~Sailor Jupiter~.mkv
Sailor Moon Crystal - 6 - Act 6. Tuxedo Mask.mkv
Sailor Moon Crystal - 7 - Act 7. Mamoru Chiba ~Tuxedo Mask~.mkv
Sailor Moon Crystal - 8 - Act 8. Minako ~Sailor V~.mkv
Sailor Moon Crystal - 9 - Act 9. Serenity ~Princess~.mkv
tvdb3.id
[t1]# cat Sailor\ Moon\ Crystal/tvdb3.id
275039
```
image

image

image

**Comment by sven-7** [comment]
Yeah, that's definitely what _should_ be writing to the logs...but I can't even get an htm log to generate.  I would not be surprised if this is a Windows issue, following the .lock files, but I can't understand why it would persist this long...sigh...

**Comment by EndOfLine369** [comment]
Found the issue. Windows can't handle "%s". I'll need to figure out what to change it too to store the lock age.
Windows:
```python
>>> datetime.datetime.now().strftime("%s")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format string
```
Linux:
```python
>>> import datetime
>>> datetime.datetime.now().strftime("%s")
'1465244319'
```

**Comment by sven-7** [comment]
I think if you change "%s" to "%S" in `strftime("%s")` that will make everything work.  I just did a test and it seems to have worked for me.

**Comment by EndOfLine369** [comment]
'%S' only provides the current second number so will get messed up if it rolls over the minute. The `time.time()` will provide epoc as well so that is what I will swap it to.
```python
WINDOWS:
>>> int(datetime.datetime.now().strftime("%s"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format string
>>> int(time.time())
1465245233

LINUX:
>>> int(datetime.datetime.now().strftime("%s"))
1465245149
>>> int(time.time())
1465245149
```

**Comment by sven-7** [comment]
Ahh - okay. Makes sense.  I only tested on some small shows, but I imagine if it hit a big one like One Piece, it'd hang.  Sounds good -- will test!

**Comment by EndOfLine369** [comment]
Thanks, let me know.
https://raw.githubusercontent.com/ZeroQI/Hama.bundle/a4dfa806c5066226b5e56cf7b65e4da0b4023c7f/Contents/Code/__init__.py

**Comment by sven-7** [comment]
About 1/4 of the way through my library (I have to take off for a bit), but it seems to be doing everything as intended.  Logs look good, scanning went as normal, and all logs generated on their own.  Let me know if you want to see any kind of logs, htm files, etc...

**Comment by EndOfLine369** [comment]
@sven-7, If it works fine for you and you give sign-off post your refresh, I think we can merge and close this out.

@MagellanSails, you have already given sign-off so will still take that :white_check_mark: unless you want to do a couple of refreshes with the latest commit.

**Comment by MagellanSails** [comment]
@EndOfLine369 Did a full refresh with the latest (`time.time`) and it ran straight through, no issues. Good to go from my perspective. 

I did notice that the HxH specials are still showing up weird, but I didn't really take a look at the logs. I'm not too concerned about it so I'm in no rush, but once I finally get around to looking at that I'll let people know what the problem was.

**Comment by sven-7** [comment]
Few comments:

- Is the missing episodes log supposed to be in any kind of order?  Mine is all over the place (not a problem, just curious).

- My Missing Plex Themes log is generating, but does not seem to be registering anything missing.  (I know this is a new one)  I know I'm missing a lot of themes, so it stands out.

- @MagellanSails My HxH logs:  `tvdbid: 252322 | Title: 'Hunter x Hunter (2011)' | Missing Specials: ['s0e1', 's0e2']`

**Comment by EndOfLine369** [comment]
@sven-7 
- There is no ordering. It is random based on the internal python dict keys.
- 'Plex themes missing' is defined so there is a file but there is no usage to populate it in the code yet thus empty.

**Comment by EndOfLine369** [comment]
@sven-7 / @MagellanSails Thanks for your time in testing.

**Comment by sven-7** [comment]
Great - thanks for the info.  No problem!

**Pull request merged**
