### PR TITLE
AniList Poster & Banner Fetching

### PR DESCRIPTION
**Pull request by BeeeQueue**
This PR adds fetching data from AniList, with help from my [arm-server](https://github.com/BeeeQueue/arm-server) API for matching AniDB->AniList IDs, with a fallback to MAL ID.

This PR only implements fetching the poster and banner, but more could easily be added.

### CODE REVIEW

**Comment by ZeroQI** [comment]
"improve import" doesn't improve anything to me, prefer the prior coding, more in line with other metadata sources code...

"Add to default prefs" make me wonder if the source shouldn't be added at the back as tvdb posters are incredibly consistent and did find Ability to miss text or quality in the few I have seen...

Apart from that, great work!
I made the engine to allow to do this kind of things easily enough...

**Comment by BeeeQueue** [comment]
✔️ fixed

I added them first so I could refetch all metadata and have every poster updated to the AniList one - should've moved it back a bit.
IMO it should definitely be up far though, it's definitely better than FanartTV and AniDB (which for some reason has super low res posters?). I also prefer them over the tvdb posters since AniList tries to have text-less posters which I prefer.

<details>
<summary>Examples - almost all of these if not all are AniList posters</summary>

image


</details>

**Comment by DJScias** [comment]
Just a curiosity in regards to this, as I'm not too well-versed with banner and poster ordering.

But does this just mean we have to add the `anilist` (any capitals?) word into the strings from `T--M 'art'` and `TS-- 'banners'`?

Or in which ones would this belong?

**Comment by BeeeQueue** [comment]
It allows adding "AniList" as a source for "posters" and "banners". 

e.g.
https://github.com/ZeroQI/Hama.bundle/blob/84bceeae6dfa93248c10584be70770c3bf4ac66b/Contents/DefaultPrefs.json#L38

**Pull request merged**
