### PR TITLE
Multiple Enhancements/Cleanups/Reductions

### PR DESCRIPTION
**Pull request by EndOfLine369**
Tied to https://github.com/ZeroQI/Absolute-Series-Scanner/pull/251

### CODE REVIEW

**Comment by EndOfLine369** [comment]
@sven-7, you can put errors seen here in your testing. I do see the error as well as I can replicate. Will take a look into the why.

**Comment by EndOfLine369** [comment]
Fixed

**Comment by sven-7** [comment]
Thanks.  Will continue to test.  Any errors (other than cache issues with the open ticket) I'll place here.

**Comment by sven-7** [comment]
Not sure this is a real error or not.

```
2019-12-02 12:09:34,799 - 36f8 - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Active Raid.agent-update.log")
2019-12-02 12:09:38,671 - 488 - Requesting 'https://api.thetvdb.com/episodes/4696453'
2019-12-02 12:09:38,769 - 488 - Downloaded URL 'https://api.thetvdb.com/episodes/4696453'
2019-12-02 12:09:38,783 - 36f8 - Requesting 'https://api.thetvdb.com/series/303730?en'
2019-12-02 12:09:38,865 - 36f8 - Downloaded URL 'https://api.thetvdb.com/series/303730?en'
2019-12-02 12:09:38,878 - 1458 - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8606'
2019-12-02 12:09:39,288 - 1458 - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8606'
2019-12-02 12:09:45,352 - 488 - Requesting 'https://api.thetvdb.com/episodes/4696454'
2019-12-02 12:09:45,457 - 488 - Downloaded URL 'https://api.thetvdb.com/episodes/4696454'
2019-12-02 12:09:45,470 - 36f8 - Requesting 'https://api.thetvdb.com/series/303730/actors'
2019-12-02 12:09:45,549 - 36f8 - Downloaded URL 'https://api.thetvdb.com/series/303730/actors'
2019-12-02 12:09:45,565 - 1458 - Requesting 'http://api.tmdb.org/3/movie/tt2064704?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en'
2019-12-02 12:09:45,865 - 1458 - Downloaded URL 'http://api.tmdb.org/3/movie/tt2064704?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en'
2019-12-02 12:09:45,885 - 488 - Requesting 'https://api.thetvdb.com/episodes/4714135'
2019-12-02 12:09:46,015 - 488 - Downloaded URL 'https://api.thetvdb.com/episodes/4714135'
2019-12-02 12:09:46,030 - 36f8 - Requesting 'https://api.thetvdb.com/series/303730/episodes?page=1'
2019-12-02 12:09:46,131 - 36f8 - Downloaded URL 'https://api.thetvdb.com/series/303730/episodes?page=1'
2019-12-02 12:09:46,148 - 1458 - Requesting 'http://webservice.fanart.tv/v3/tv/79099?api_key=cfa9dc054d221b8d107f8411cd20b13f'
2019-12-02 12:09:46,480 - 1458 - Downloaded URL 'http://webservice.fanart.tv/v3/tv/79099?api_key=cfa9dc054d221b8d107f8411cd20b13f'
2019-12-02 12:09:46,513 - 488 - Requesting 'https://api.thetvdb.com/episodes/4714136'
2019-12-02 12:09:46,605 - 488 - Downloaded URL 'https://api.thetvdb.com/episodes/4714136'
2019-12-02 12:09:46,625 - 36f8 - Requesting 'https://api.thetvdb.com/episodes/5427418'
2019-12-02 12:09:46,740 - 1458 - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-79099?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-e67a4e892\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1089, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 162, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 147, in Update
    dict_AniDB, ANNid, MALid                                    =       AniDB.GetMetadata(media, movie, error_log,       source, AniDBid, TVDBid, AnimeLists.AniDBMovieSets, mappingList)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\AniDB.py", line 317, in GetMetadata
    elif epNumType in ['1', '2']:   SaveDict([episode],   missing,         season)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2007-07' does not match format '%Y-%m-%d'

```

```
2019-12-04 17:46:32,874 - d8c - Requesting 'http://127.0.0.1:32400/library/metadata/373407/tree'
2019-12-04 17:46:33,048 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=3420'
2019-12-04 17:46:33,122 - d8c - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Ace of the Diamond.agent-search.log")
2019-12-04 17:46:33,138 - d8c - Sending packed state data (104 bytes)
2019-12-04 17:46:33,138 - d8c - Response: [200] str, 656 bytes
2019-12-04 17:46:39,069 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=4634'
2019-12-04 17:46:39,312 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=4634'
2019-12-04 17:46:40,904 - 494 - Serializing to C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\f\eaaa53c983fa72cbd2b0a5fbd236d3dc2df1b52.bundle\Contents\com.plexapp.agents.hama\Info.xml
2019-12-04 17:46:40,918 - 494 - Sending packed state data (580 bytes)
2019-12-04 17:46:40,918 - 494 - Response: [200] str, 16 bytes
2019-12-04 17:46:45,338 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5367'
2019-12-04 17:46:45,584 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5367'
2019-12-04 17:46:51,605 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5698'
2019-12-04 17:46:51,828 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=5698'
2019-12-04 17:46:57,845 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=6065'
2019-12-04 17:46:58,069 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=6065'
2019-12-04 17:47:04,095 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8713'
2019-12-04 17:47:04,325 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=8713'
2019-12-04 17:47:10,344 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=9458'
2019-12-04 17:47:10,592 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=9458'
2019-12-04 17:47:16,611 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=9937'
2019-12-04 17:47:16,858 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=9937'
2019-12-04 17:47:22,880 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10021'
2019-12-04 17:47:23,107 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10021'
2019-12-04 17:47:29,127 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10535'
2019-12-04 17:47:29,408 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10535'
2019-12-04 17:47:35,428 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10882'
2019-12-04 17:47:35,829 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=10882'
2019-12-04 17:47:41,901 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11839'
2019-12-04 17:47:42,194 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11839'
2019-12-04 17:47:48,219 - f7c - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13266'
2019-12-04 17:47:48,617 - f7c - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=13266'
2019-12-04 17:47:55,283 - f7c - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-71863?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-5a96726d0\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1089, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 162, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 147, in Update
    dict_AniDB, ANNid, MALid                                    =       AniDB.GetMetadata(media, movie, error_log,       source, AniDBid, TVDBid, AnimeLists.AniDBMovieSets, mappingList)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\AniDB.py", line 374, in GetMetadata
    Log.Info("ANNid: '%s', MALid: '%s', xml loaded: '%s'" % (ANNid, MALid, str(xml is not None)))
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '1969' does not match format '%Y-%m-%d'

2019-12-04 17:47:59,953 - f7c - Serializing to C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\1\5e35c75b994bc9c366f706f6e366a4c0932974e.bundle\Contents\com.plexapp.agents.hama\Info.xml
2019-12-04 17:47:59,963 - f7c - Sending packed state data (580 bytes)
2019-12-04 17:47:59,963 - f7c - Response: [200] str, 16 bytes

```

**Comment by EndOfLine369** [comment]
Fixed.
From new code for smart cache checking the series end date.
```python
      enddate = datetime.datetime.strptime(GetXml(xml, 'enddate') or datetime.datetime.now().strftime("%Y-%m-%d"), '%Y-%m-%d')
```
Can't handle incomplete date data.
`ValueError: time data '2007-07' does not match format '%Y-%m-%d'`
image
`ValueError: time data '1969' does not match format '%Y-%m-%d'`
image

```python
>>> ed = '2017'
>>> datetime.datetime.strptime("{}-12-31".format(ed) if len(ed)==4 else "{}-30".format(ed) if len(ed)==7 else ed, '%Y-%m-%d')
datetime.datetime(2017, 12, 31, 0, 0)
>>> ed = '2017-03' 
>>> datetime.datetime.strptime("{}-12-31".format(ed) if len(ed)==4 else "{}-30".format(ed) if len(ed)==7 else ed, '%Y-%m-%d')
datetime.datetime(2017, 3, 30, 0, 0)
>>> ed = '2017-03-02' 
>>> datetime.datetime.strptime("{}-12-31".format(ed) if len(ed)==4 else "{}-30".format(ed) if len(ed)==7 else ed, '%Y-%m-%d')
datetime.datetime(2017, 3, 2, 0, 0)
```

**Pull request merged**
