### PR TITLE
Remove .gitmodules

### PR DESCRIPTION
**Pull request by jrobeson**
I don't think you're using this, but if you are, then you can close this PR.

### CODE REVIEW

**Comment by ZeroQI** [comment]
i am unsure about this to be honest. i do use two of the xml files for mapping anidbid to the tvdbid and the movie collection, but the agent code allow to download them automatically... I did however want to show i am using the files in some way...

**Comment by jrobeson** [comment]
do you ever run the git submodule commands ever?

**Comment by ZeroQI** [comment]
no. i just past the code on github by hand...
i am really very novice with github.. I can't even delete the release i have created to be fair

**Comment by ZeroQI** [comment]
the 0.6.1 and 0.5.2 ones in there https://github.com/ZeroQI/Hama.bundle/releases...
if you also know how. i guess you will tell me to remothe the file then since i don't use the git submodule command...

**Pull request merged**
